// packages/ui-qwik/src/components/elements/ColorPicker.tsx
import type { PropsOf, QRL } from '@qwik.dev/core';
import { $, component$, useStore } from '@qwik.dev/core';
import {
  getBrightness,
  hexToRgba,
  hsvToRgb,
  rgbToHex,
  rgbToHsv,
  clamp,
  getMousePosition,
} from '../../utils/color';
import { Shuffle } from '~/svg/Shuffle';
import { getClassObject } from '../functions';

export interface ColorPickerProps
  extends Omit<PropsOf<'div'>, | 'onInput$'> {
  onInput$?: QRL<(color: string) => void>;
  value?: string;
  colors?: string[];
  preview?: 'left' | 'right' | 'top' | 'bottom' | 'full';
  horizontal?: boolean;
  showInput?: boolean;
  opacity?: boolean;
}

export const ColorPicker = component$<ColorPickerProps>(
  ({
    id,
    class: Class,
    value = '#000000',
    colors = [
      '#FAEDCB',
      '#C9E4DE',
      '#C6DEF1',
      '#DBCDF0',
      '#F2C6DE',
      '#FCD05C',
      '#5FE2C5',
      '#4498DB',
      '#9863E7',
      '#E43A96',
      '#000000',
      '#555555',
      '#AAAAAA',
      '#FFFFFF',
    ],
    onInput$,
    preview = 'left',
    horizontal,
    showInput = true,
    opacity
  }) => {
    const height = 150;
    const width = height - 25;
    const maxHue = height - 2;

    const hsvColor = rgbToHsv(hexToRgba(value));
    const store = useStore({
      hue: {
        position: hsvColor.h * maxHue,
        color: rgbToHex(hsvToRgb({ h: hsvColor.h, s: 1, v: 1 })),
      },
      opacity: {
        position: hsvColor.a !== undefined ? (1 - hsvColor.a) * maxHue : 0,
      },
      bPosition: (1 - hsvColor.v) * maxHue,
      sPosition: hsvColor.s * width,
      value: value,
    });

    const setColor = $(async (color: string) => {
      if (!/^#[0-9a-f]{0,8}$/i.test(color)) return;
      const hsv = rgbToHsv(hexToRgba(color));
      store.hue.position = hsv.h * maxHue;
      store.hue.color = rgbToHex(hsvToRgb({ h: hsv.h, s: 1, v: 1, a: hsv.a }));
      store.sPosition = hsv.s * width;
      store.bPosition = (1 - hsv.v) * maxHue;

      store.value = color;
      await onInput$?.(store.value);
    });

    const hueMouseDown = $(
      async (e: MouseEvent | TouchEvent, el: HTMLDivElement) => {
        const hOffset = el.getBoundingClientRect().top;
        const hueChange = async (e: MouseEvent | TouchEvent, hOffset: number) => {
          const { y } = getMousePosition(e);
          store.hue.position = clamp(maxHue - (y - hOffset), 0, maxHue);
          const hsvColor = rgbToHsv(hexToRgba((store.value)));
          const h = store.hue.position / maxHue;
          hsvColor.h = h;
          store.hue.color = rgbToHex(hsvToRgb({ h, s: 1, v: 1, a: hsvColor.a }));

          store.value = rgbToHex(hsvToRgb(hsvColor));
          await onInput$?.(store.value);
        };

        await hueChange(e, hOffset);
        const eventListener = (e: MouseEvent | TouchEvent) =>
          void hueChange(e, hOffset);
        window.addEventListener('mousemove', eventListener);
        window.addEventListener('touchmove', eventListener);
        const mouseUpListener = () => {
          window.removeEventListener('mousemove', eventListener);
          window.removeEventListener('touchmove', eventListener);
          window.removeEventListener('mouseup', mouseUpListener);
          window.removeEventListener('touchend', mouseUpListener);
        };
        window.addEventListener('mouseup', mouseUpListener);
        window.addEventListener('touchend', mouseUpListener);
      },
    );

    const sbMouseDown = $(
      async (e: MouseEvent | TouchEvent, el: HTMLDivElement) => {
        const offset = el.getBoundingClientRect();
        const sbChange = async (e: MouseEvent | TouchEvent, hOffset: DOMRect) => {
          const { x, y } = getMousePosition(e);
          store.bPosition = clamp(y - hOffset.top, 0, maxHue);
          store.sPosition = clamp(x - hOffset.left, 0, width);
          const s = store.sPosition / width;
          const v = 1 - store.bPosition / maxHue;

          store.value = rgbToHex(
            hsvToRgb({
              h: store.hue.position / maxHue,
              s,
              v,
              a: store.opacity.position !== undefined ? 1 - store.opacity.position / maxHue : 1,
            }),
          );
          await onInput$?.(store.value);
        };

        await sbChange(e, offset);
        const eventListener = (e: MouseEvent | TouchEvent) =>
          void sbChange(e, offset);
        window.addEventListener('mousemove', eventListener);
        window.addEventListener('touchmove', eventListener);
        const mouseUpListener = () => {
          window.removeEventListener('mousemove', eventListener);
          window.removeEventListener('touchmove', eventListener);
          window.removeEventListener('mouseup', mouseUpListener);
          window.removeEventListener('touchend', mouseUpListener);
        };
        window.addEventListener('mouseup', mouseUpListener);
        window.addEventListener('touchend', mouseUpListener);
      },
    );

    const opacityMouseDown = $(
      async (e: MouseEvent | TouchEvent, el: HTMLDivElement) => {
        const offset = el.getBoundingClientRect();
        const opacityChange = async (e: MouseEvent | TouchEvent, hOffset: DOMRect) => {
          const { x } = getMousePosition(e);
          store.opacity.position = clamp(x - hOffset.left, 0, maxHue);
          const a = 1 - (store.opacity.position / maxHue);
          const hsvColor = rgbToHsv(hexToRgba((store.value)));
          hsvColor.a = a;
          store.value = rgbToHex(hsvToRgb(hsvColor));
          await onInput$?.(store.value);
        };

        await opacityChange(e, offset);
        const eventListener = (e: MouseEvent | TouchEvent) =>
          void opacityChange(e, offset);
        window.addEventListener('mousemove', eventListener);
        window.addEventListener('touchmove', eventListener);
        const mouseUpListener = () => {
          window.removeEventListener('mousemove', eventListener);
          window.removeEventListener('touchmove', eventListener);
          window.removeEventListener('mouseup', mouseUpListener);
          window.removeEventListener('touchend', mouseUpListener);
        };
        window.addEventListener('mouseup', mouseUpListener);
        window.addEventListener('touchend', mouseUpListener);
      },
    );


    return (
      <div
        class={{
          'lum-card touch-none p-4': true,
          'flex-col': !horizontal,
          ...getClassObject(Class),
        }}
        id={id}
        onInput$={async (e, el) => {
          if (!el.dataset.value) return;
          await setColor(el.dataset.value);
        }}
      >
        <div class="flex gap-4">
          <div
            class="relative h-37.5 w-31.25 rounded-md"
            style={{
              background: `linear-gradient(to right, #FFFFFF, ${store.hue.color})`,
            }}
            onMouseDown$={sbMouseDown}
            onTouchStart$={sbMouseDown}
            preventdefault:mousedown
            preventdefault:touchstart
          >
            <div class="h-37.5 w-31.25 rounded-md border border-gray-700 bg-linear-to-b from-transparent to-black" />
            <div
              class={{
                'absolute -top-2 -left-2 h-4 w-4 rounded-md border lum-bg drop-shadow-lg':
                  true,
              }}
              style={{
                '--bg-color': store.value,
                transform: `translate(${store.sPosition}px, ${store.bPosition}px)`,
              }}
            />
          </div>
          <div
            class="relative h-37.5 w-2 rounded-md border border-gray-700"
            style={{
              background:
                'linear-gradient(to bottom, #ff0000, #ff00ff, #0000ff, #00ffff, #00ff00, #ffff00, #ff0000)',
            }}
            onMouseDown$={hueMouseDown}
            onTouchStart$={hueMouseDown}
            preventdefault:mousedown
            preventdefault:touchstart
          >
            <div
              class="absolute -bottom-2 -left-1.25 h-4 w-4 rounded-md lum-bg! bg-[#ff0000] "
              style={{
                transform: `translateY(${-store.hue.position}px)`,
                '--bg-color': store.hue.color,
              }}
            />
          </div>
        </div>
        {opacity && (
          <div
            class="relative h-2 w-full rounded-md"
            onMouseDown$={opacityMouseDown}
            onTouchStart$={opacityMouseDown}
            preventdefault:mousedown
            preventdefault:touchstart
            style={{
              backgroundColor: 'white',
              backgroundImage: `
                linear-gradient(45deg, #ccc 25%, transparent 25%), 
                linear-gradient(135deg, #ccc 25%, transparent 25%),
                linear-gradient(45deg, transparent 75%, #ccc 75%),
                linear-gradient(135deg, transparent 75%, #ccc 75%);
              `,
              backgroundSize: '8px 8px',
              backgroundPosition: '0 0, 4px 0, 4px -4px, 0 4px',
            }}
          >
            <div
              class="alsolute inset-0 h-2 w-full rounded-md border border-gray-700"
              style={{
                background: `linear-gradient(to right, ${store.value}, transparent)`,
              }}
            />
            <div
              class="absolute -bottom-1.25 -left-1.25 h-4 w-4 rounded-md"
              style={{
                transform: `translateX(${store.opacity.position ?? 1}px)`,
                backgroundColor: store.value,
                backgroundImage: `
                  linear-gradient(45deg, #ccc4 25%, transparent 25%), 
                  linear-gradient(135deg, #ccc4 25%, transparent 25%),
                  linear-gradient(45deg, transparent 75%, #ccc4 75%),
                  linear-gradient(135deg, transparent 75%, #ccc4 75%);
                `,
                backgroundSize: '8px 8px',
                backgroundPosition: '0 0, 4px 0, 4px -4px, 0 4px',
              }}
            />
          </div>
        )}
        <div class="flex w-37.5 flex-wrap justify-between gap-1">
          {showInput && (
            <div
              class={{
                'mb-2 flex w-37.5 border-b border-b-gray-700 pb-3': true,
                'flex-row gap-1': preview == 'left',
                'flex-row-reverse gap-1': preview == 'right',
                'flex-col': preview == 'top',
                'flex-col-reverse': preview == 'bottom',
              }}
            >
              {preview != 'full' && (
                <div
                  class={{
                    'border border-gray-700 rounded-sm': true,
                    'aspect-square h-full':
                      preview == 'left' || preview == 'right',
                    'h-3 w-full': preview == 'top' || preview == 'bottom',
                    'rounded-b-none': preview == 'top',
                    'rounded-t-none': preview == 'bottom',
                  }}
                  style={{
                    backgroundColor: `${store.value}`,
                  }}
                ></div>
              )}
              <input
                class={{
                  'lum-input w-full p-1 text-xs rounded-sm': true,
                  'rounded-t-none border-t-0': preview == 'top',
                  'rounded-b-none border-b-0': preview == 'bottom',
                }}
                value={store.value}
                style={
                  preview == 'full'
                    ? {
                      backgroundColor: `${store.value}`,
                      color:
                          getBrightness(
                            hexToRgba((store.value)),
                          ) > 0.5
                            ? 'black'
                            : 'white',
                    }
                    : {}
                }
                onInput$={async (e, el) => {
                  await setColor(el.value);
                }}
              />
            </div>
          )}
          {colors.map((color, i) => {
            return (
              <button type="button"
                key={i}
                name={color}
                class={{
                  'lum-btn rounded-sm h-[1.6rem] w-[1.6rem] p-0 lum-bg hover:brightness-150': true,
                  'border-lum-accent': color === store.value,
                }}
                style={{
                  '--bg-color': color,
                }}
                onClick$={async () => {
                  await setColor(color);
                }}
              ></button>
            );
          })}
          <button type="button"
            class="lum-btn rounded-sm h-[1.6rem] w-[1.6rem] p-0.5"
            name="Randomize"
            onClick$={async () => {
              const color = `#${Math.floor(Math.random() * 16777215).toString(16)}`;
              await setColor(color);
            }}
          >
            <Shuffle class="p-0.5 pl-0.5 text-lum-text" />
          </button>
        </div>
      </div>
    );
  },
);

// packages/ui-react/src/components/elements/ColorPicker.tsx
import type React from 'react';
import { useState, useEffect } from 'react';
import { ShuffleIcon } from 'lucide-react';
import {
  clamp,
  getMousePosition,
  hexToRgba,
  hsvToRgb,
  rgbToHex,
  rgbToHsv,
} from '../../utils/color';
import { getClasses } from '../functions';

export interface ColorPickerProps extends Omit<
  React.HTMLAttributes<HTMLDivElement>,
  'onInput'
> {
  onInput?: (color: string) => void;
  value?: string;
  colors?: string[];
  preview?: 'left' | 'right' | 'top' | 'bottom' | 'full';
  horizontal?: boolean;
  showInput?: boolean;
  opacity?: boolean;
}

export function ColorPicker({
  id,
  className,
  value = '#000000',
  colors = [
    '#FAEDCB',
    '#C9E4DE',
    '#C6DEF1',
    '#DBCDF0',
    '#F2C6DE',
    '#FCD05C',
    '#5FE2C5',
    '#4498DB',
    '#9863E7',
    '#E43A96',
    '#000000',
    '#555555',
    '#AAAAAA',
    '#FFFFFF',
  ],
  onInput,
  preview = 'left',
  horizontal,
  showInput = true,
  opacity,
  ...props
}: ColorPickerProps) {
  const height = 150;
  const width = height - 25;
  const maxHue = height - 2;

  const [colorValue, setColorValue] = useState(value);
  const hsvColor = rgbToHsv(hexToRgba(colorValue));

  const [huePos, setHuePos] = useState(hsvColor.h * maxHue);
  const [hueColor, setHueColor] = useState(
    rgbToHex(hsvToRgb({ h: hsvColor.h, s: 1, v: 1 }))
  );
  const [bPos, setBPos] = useState((1 - hsvColor.v) * maxHue);
  const [sPos, setSPos] = useState(hsvColor.s * width);

  useEffect(() => {
    setColorValue(value);
    const hsv = rgbToHsv(hexToRgba(value));
    setHuePos(hsv.h * maxHue);
    setHueColor(rgbToHex(hsvToRgb({ h: hsv.h, s: 1, v: 1, a: hsv.a })));
    setSPos(hsv.s * width);
    setBPos((1 - hsv.v) * maxHue);
  }, [value, maxHue, width]);

  const updateColor = (newColor: string) => {
    if (!/^#[0-9a-f]{0,8}$/i.test(newColor)) return;
    setColorValue(newColor);
    const hsv = rgbToHsv(hexToRgba(newColor));
    setHuePos(hsv.h * maxHue);
    setHueColor(rgbToHex(hsvToRgb({ h: hsv.h, s: 1, v: 1, a: hsv.a })));
    setSPos(hsv.s * width);
    setBPos((1 - hsv.v) * maxHue);
    if (onInput) onInput(newColor);
  };

  const handleHueMouseDown = (
    e: React.MouseEvent<HTMLDivElement> | React.TouchEvent<HTMLDivElement>
  ) => {
    const el = e.currentTarget;
    const hOffset = el.getBoundingClientRect().top;
    const updateHue = (evt: MouseEvent | TouchEvent) => {
      const { y } = getMousePosition(evt);
      const pos = clamp(maxHue - (y - hOffset), 0, maxHue);
      setHuePos(pos);
      const h = pos / maxHue;
      const hsv = rgbToHsv(hexToRgba(colorValue));
      hsv.h = h;
      setHueColor(rgbToHex(hsvToRgb({ h, s: 1, v: 1, a: hsv.a })));
      const hex = rgbToHex(hsvToRgb(hsv));
      setColorValue(hex);
      if (onInput) onInput(hex);
    };

    updateHue(e.nativeEvent);
    const onMove = (evt: MouseEvent | TouchEvent) => updateHue(evt);
    const onUp = () => {
      window.removeEventListener('mousemove', onMove);
      window.removeEventListener('mouseup', onUp);
      window.removeEventListener('touchmove', onMove);
      window.removeEventListener('touchend', onUp);
    };
    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onUp);
    window.addEventListener('touchmove', onMove);
    window.addEventListener('touchend', onUp);
  };

  const handleSatMouseDown = (
    e: React.MouseEvent<HTMLDivElement> | React.TouchEvent<HTMLDivElement>
  ) => {
    const el = e.currentTarget;
    const rect = el.getBoundingClientRect();
    const updateSat = (evt: MouseEvent | TouchEvent) => {
      const { x, y } = getMousePosition(evt);
      const s = clamp(x - rect.left, 0, width);
      const b = clamp(maxHue - (y - rect.top), 0, maxHue);
      setSPos(s);
      setBPos(maxHue - b);

      const hsv = rgbToHsv(hexToRgba(colorValue));
      hsv.s = s / width;
      hsv.v = b / maxHue;

      const hex = rgbToHex(hsvToRgb(hsv));
      setColorValue(hex);
      if (onInput) onInput(hex);
    };

    updateSat(e.nativeEvent);
    const onMove = (evt: MouseEvent | TouchEvent) => updateSat(evt);
    const onUp = () => {
      window.removeEventListener('mousemove', onMove);
      window.removeEventListener('mouseup', onUp);
      window.removeEventListener('touchmove', onMove);
      window.removeEventListener('touchend', onUp);
    };
    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onUp);
    window.addEventListener('touchmove', onMove);
    window.addEventListener('touchend', onUp);
  };

  return (
    <div
      {...props}
      className={getClasses({
        'flex flex-col gap-2 p-2': true,
        [className ?? '']: !!className,
      })}
    >
      <div className="flex gap-2">
        <div
          className="relative cursor-pointer rounded-sm"
          style={{
            width: `${width}px`,
            height: `${height}px`,
            backgroundColor: hueColor,
          }}
          onMouseDown={handleSatMouseDown}
          onTouchStart={handleSatMouseDown}
        >
          <div className="absolute inset-0 bg-gradient-to-r from-white to-transparent" />
          <div className="absolute inset-0 bg-gradient-to-t from-black to-transparent" />
          <div
            className="absolute h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white shadow-sm"
            style={{
              left: `${sPos}px`,
              top: `${bPos}px`,
              backgroundColor: colorValue,
            }}
          />
        </div>

        <div
          className="relative h-full w-5 cursor-pointer rounded-sm"
          style={{
            height: `${height}px`,
            background:
              'linear-gradient(to top, #ff0000, #ff00ff, #0000ff, #00ffff, #00ff00, #ffff00, #ff0000)',
          }}
          onMouseDown={handleHueMouseDown}
          onTouchStart={handleHueMouseDown}
        >
          <div
            className="absolute left-0 h-1.5 w-full -translate-y-1/2 rounded-sm border border-white bg-black/40 shadow-sm"
            style={{ top: `${maxHue - huePos}px` }}
          />
        </div>
      </div>

      {showInput && (
        <div className="flex items-center gap-2">
          <input
            type="text"
            className="lum-input lum-input-p-1 text-lum-text w-full rounded-sm text-center text-sm"
            value={colorValue}
            onChange={(e) => updateColor(e.target.value)}
          />
          <button
            type="button"
            className="lum-btn rounded-sm p-1.5"
            aria-label="Randomize color"
            onClick={() => {
              const randomHex =
                '#' +
                Math.floor(Math.random() * 16777215)
                  .toString(16)
                  .padStart(6, '0')
                  .toUpperCase();
              updateColor(randomHex);
            }}
          >
            <ShuffleIcon size={16} />
          </button>
        </div>
      )}

      {colors && colors.length > 0 && (
        <div className="flex flex-wrap gap-1.5 pt-1">
          {colors.map((c, i) => (
            <button
              key={i}
              type="button"
              className="h-5 w-5 rounded-sm border border-black/20 transition-transform hover:scale-110"
              style={{ backgroundColor: c }}
              onClick={() => updateColor(c)}
            />
          ))}
        </div>
      )}
    </div>
  );
}
