// packages/ui-qwik/src/components/elements/Label.tsx
import type { PropsOf } from '@qwik.dev/core';
import { component$, Slot } from '@qwik.dev/core';
import { getClassObject } from '../functions';

interface LabelProps extends PropsOf<'label'> {
  label?: string,
  outerProps?: PropsOf<'div'>,
}

export const Label = component$<LabelProps>(({
  label,
  outerProps,
  ...props
}) => {
  return (
    <div style={{
        gap: "var(--lum-label-gap)",
      }}
      {...outerProps}
      class={{
        "flex flex-col": true,
        ...getClassObject(outerProps?.class),
      }}
    >
      <label {...props} class={{
        "text-lum-text select-none flex items-center gap-1": true,
        ...getClassObject(props.class),
      }}>
        <Slot name="before-label" />
        {label}
        <Slot name="after-label" />
      </label>
      <Slot />
    </div>
  );
});

// packages/ui-react/src/components/elements/Label.tsx
import type React from 'react';
import { getClasses } from '../functions';

export interface LabelProps extends React.LabelHTMLAttributes<HTMLLabelElement> {
  label?: React.ReactNode;
  beforeLabel?: React.ReactNode;
  afterLabel?: React.ReactNode;
  outerProps?: React.HTMLAttributes<HTMLDivElement>;
  children?: React.ReactNode;
}

export function Label({
  label,
  beforeLabel,
  afterLabel,
  outerProps,
  className,
  children,
  ...props
}: LabelProps) {
  return (
    <div
      style={{
        gap: 'var(--lum-label-gap)',
      }}
      {...outerProps}
      className={getClasses({
        'flex flex-col': true,
        [outerProps?.className ?? '']: !!outerProps?.className,
      })}
    >
      <label
        {...props}
        className={getClasses({
          'text-lum-text flex items-center gap-1 select-none': true,
          [className ?? '']: !!className,
        })}
      >
        {beforeLabel}
        {label}
        {afterLabel}
      </label>
      {children}
    </div>
  );
}
