// packages/ui-docs/src/components/Nav.tsx
import { component$ } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';
import { LogoDiscord, LogoLuminescentFull, Nav } from '@luminescent/ui-qwik';
import { Book, Github } from 'lucide-icons-qwik';

export default component$(() => {
  return (
    <Nav floating fixed colorClass="lum-bg-lum-input-bg/50 !text-lum-text" style={{
      '--lum-border-radius': '1rem',
    }}>
      <Link q:slot="start" href="/" class="lum-btn lum-bg-transparent rounded-lum-2">
        <div
          class="flex items-center gap-1 fill-[#f0ccfb] font-semibold text-[#f0ccfb]"
          style="filter: drop-shadow(0 0 1rem #CB6CE6);"
        >
          <LogoLuminescentFull size={20} />
        </div>
      </Link>

      <Link
        q:slot="end"
        href="/docs"
        class={{
          'lum-btn lum-bg-transparent hidden sm:flex rounded-lum-2 text-sm': true,
        }}
      >
        <Book size={20} /> Docs
      </Link>
      <a
        q:slot="end"
        href="https://luminescent.dev"
        class="lum-btn lum-bg-transparent rounded-lum-2"
      >
        <LogoLuminescentFull size={20} />
      </a>
      <div q:slot="end" class="hidden gap-2 sm:flex">
        <SocialButtons />
      </div>

      <Link q:slot="mobile" href="/docs" class="lum-btn lum-bg-transparent rounded-lum-2">
        <Book size={20} /> Docs
      </Link>
      <a
        q:slot="mobile"
        href="https://luminescent.dev"
        class="lum-btn lum-bg-transparent"
      >
        <div class="flex items-center gap-1 font-semibold">
          <LogoLuminescentFull size={20} class="mt-1" />
        </div>
      </a>
      <div q:slot="mobile" class="flex justify-evenly">
        <SocialButtons />
      </div>
    </Nav>
  );
});

export const SocialButtons = component$(() => {
  return (
    <>
      <a
        href="https://github.com/LuminescentDev"
        title="GitHub"
        class="lum-btn lum-bg-transparent p-2 rounded-lum-2"
      >
        <Github size={20} />
      </a>
      <a href="/discord" title="Discord" class="lum-btn lum-bg-transparent p-2 rounded-lum-2">
        <LogoDiscord size={20} />
      </a>
    </>
  );
});

// packages/ui-react/src/components/elements/Nav.tsx
import { MenuIcon } from 'lucide-react';
import { getClasses } from '../functions';
import type React from 'react';
import { useState } from 'react';

interface NavProps
  extends Omit<
    React.HTMLAttributes<HTMLElement>,
    'bind:checked' | 'type' | 'children'
  > {
  class?: { [key: string]: boolean };
  fixed?: boolean;
  floating?: boolean;
  nohamburger?: boolean;
  start?: React.ReactNode;
  center?: React.ReactNode;
  end?: React.ReactNode;
  mobile?: React.ReactNode;
  colorClass?: string;
}

export function Nav({
  fixed,
  floating,
  nohamburger,
  colorClass = 'lum-bg-lum-card-bg',
  start,
  center,
  end,
  mobile,
  ...props
}: NavProps) {
  const [menu, setMenu] = useState(false);

  return (
    <nav
      {...props}
      className={getClasses({
        'top-0 left-0 z-50 flex w-full flex-col duration-200 motion-safe:transition-all':
          true,
        fixed: fixed,
        absolute: !fixed,
        ...props.class,
      })}
    >
      {!nohamburger && (
        <div
          className={getClasses({
            'absolute top-full flex w-full flex-col items-center px-2 motion-safe:transition-all sm:hidden':
              true,
            'mt-2': menu,
            'pointer-events-none opacity-0': !menu,
            'before:backdrop-blur-lg': !colorClass.includes('transparent'),
            'before:absolute before:-z-10 before:h-full before:w-full before:rounded-lum before:drop-shadow-xl before:content-[""]':
              true,
          })}
        >
          <div
            className={getClasses({
              [colorClass]: true,
              'flex w-full max-w-7xl flex-col gap-2 rounded-lum border px-2 py-4 motion-safe:transition-all':
                true,
            })}
          >
            {mobile}
          </div>
        </div>
      )}
      <div
        className={getClasses({
          [colorClass]: !floating,
          '!border-x-0 !border-t-0': !floating,
          'before:backdrop-blur-lg':
            !colorClass.includes('transparent') && !floating,
          'before:absolute before:-z-10 before:h-full before:w-full before:drop-shadow-xl before:content-[""]':
            !floating,
          'relative mx-2 mt-2': floating,
        })}
      >
        <div
          className={getClasses({
            'mx-auto flex w-full max-w-7xl justify-evenly px-2': true,
            [colorClass]: floating,
            'rounded-lum border': floating,
            'before:backdrop-blur-lg':
              !colorClass.includes('transparent') && floating,
            'before:absolute before:-z-10 before:h-full before:w-full before:max-w-7xl before:rounded-lum before:drop-shadow-xl before:content-[""]':
              floating,
          })}
        >
          {start && (
            <div className="flex flex-1 items-center justify-start gap-2 py-2">
              {start}
            </div>
          )}
          {center && (
            <div className="flex flex-1 items-center justify-center gap-2 py-2">
              {center}
            </div>
          )}
          {end && (
            <div className="flex flex-1 items-center justify-end gap-2 py-2">
              {end}
            </div>
          )}
          {!nohamburger && (
            <button
              className={'lum-btn lum-bg-transparent p-2 sm:hidden'}
              onClick={() => setMenu(!menu)}
            >
              <MenuIcon size={24} />
            </button>
          )}
        </div>
      </div>
    </nav>
  );
};
