// packages/ui-qwik/src/components/elements/SelectMenu.tsx
import type { JSXChildren, PropsOf } from '@qwik.dev/core';
import { component$, Slot, useSignal, useStore } from '@qwik.dev/core';
import { Dropdown } from './Dropdown';
import { getClassObject } from '../functions';

interface SelectMenuProps extends PropsOf<'select'> {
  panelClass?: string;
  btnClass?: string;
  noblur?: boolean;
  nocloseonclick?: boolean;
  customDropdown?: boolean;
  hover?: boolean;
  align?: 'left' | 'right' | 'center';
  values?: {
    name: JSXChildren;
    value: string | number;
  }[];
}

export const SelectMenu = component$<SelectMenuProps>((props) => {
  return (
    <div class="flex flex-col">
      <label for={props.id ? `${props.id}-dropdown` : undefined} class="pb-1 text-lum-text select-none">
        <Slot />
      </label>
      <SelectMenuRaw {...props}>
        <div q:slot="dropdown">
          {(props.customDropdown || !props.values?.length) && <Slot name="dropdown" />}
        </div>
        <div q:slot="extra-buttons">
          <Slot name="extra-buttons" />
        </div>
      </SelectMenuRaw>
    </div>
  );
});

export const SelectMenuRaw = component$<SelectMenuProps>(({
  values,
  class: Class,
  panelClass = 'lum-bg-lum-input-bg',
  btnClass = 'lum-bg-transparent',
  noblur,
  nocloseonclick,
  customDropdown,
  hover,
  align,
  ...props
}) => {
  const store = useStore({
    opened: false,
    value: props.value,
  });
  const selectRef = useSignal<HTMLSelectElement>();
  const selected = values?.find(v => v.value === store.value);

  return (
    <div
      class={{
        'relative touch-manipulation': true,
        group: hover,
      }}
    >
      {values && (
        <select
          {...props}
          ref={selectRef}
          class="hidden"
        >
          {values.map((value, i) => {
            return (
              <option key={i} value={value.value}>{`${value.value}`}</option>
            );
          })}
        </select>
      )}
      <Dropdown
        id={props.id ? `${props.id}-dropdown` : undefined}
        opened={store.opened}
        class={{
          'w-full': true,
          ...getClassObject(Class),
        }}
        onClick$={(e, el) => {
          if (hover) return; // do not toggle on click if hover is enabled
          store.opened = !store.opened;
          if (nocloseonclick) return; // do not close on click if nocloseonclick is true
          // close on click
          const listener = (e: MouseEvent) => {
            // if the dropdown is already closed, remove the listener
            if (!store.opened) return document.removeEventListener('click', listener);

            // check if the click is outside the button
            const path = e.composedPath();
            if (path.includes(el)) return;

            // close the dropdown and remove the listener
            store.opened = false;
            document.removeEventListener('click', listener);
          };
          document.addEventListener('click', listener);
        }}
      >
        {customDropdown && <Slot name="dropdown"/>}
        {!customDropdown && (selected?.name ?? values?.[0]?.name ?? <Slot name="dropdown" />)}
      </Dropdown>
      {hover && <div class="h-2 absolute w-full" />}
      <div class={{
        'absolute z-1000 mt-2': true,
        'backdrop-blur-lg': !noblur,
        'lum-scroll flex max-h-72 flex-col gap-1 overflow-auto rounded-lum border p-1 select-none motion-safe:transition-all ease-out': true,
        'left-0': align === 'left',
        'right-0': align === 'right',
        'left-1/2 -translate-x-1/2': align === 'center',
        'pointer-events-none scale-95 opacity-0': !store.opened,
        'duration-300 group-hover:pointer-events-auto group-hover:scale-100 group-hover:opacity-100 group-hover:duration-75': hover,
        'focus-within:pointer-events-auto focus-within:scale-100 focus-within:opacity-100 focus-within:duration-75': true,
        [panelClass]: true,
      }}
      >
        {values?.map(({ name, value }, i) => {
          return (
            <button type="button"
              class={{
                'lum-btn rounded-lum-1': true,
                [btnClass]: true,
              }}
              key={i}
              onClick$={(e, el) => {
                // close the dropdown
                el.blur();
                store.opened = false;

                // set the value of the select element
                const select = selectRef.value;
                if (select) {
                  select.value = value.toString();
                  select.dispatchEvent(new Event('change'));
                }
                store.value = value.toString();
              }}
            >
              {name}
            </button>
          );
        })}
        <Slot name="extra-buttons" />
      </div>
    </div>
  );
});

// packages/ui-react/src/components/elements/SelectMenu.tsx
import type React from 'react';
import { getClasses } from '../functions';
import { Dropdown } from './Dropdown';
import { useRef, useState } from 'react';

interface SelectMenuProps
  extends React.SelectHTMLAttributes<HTMLSelectElement> {
  customDropdown?: boolean;
  panelClass?: string;
  btnClass?: string;
  noblur?: boolean;
  nocloseonclick?: boolean;
  hover?: boolean;
  align?: 'left' | 'right' | 'center';
  values?: {
    name: React.ReactNode;
    value: string | number;
  }[];
  dropdown?: React.ReactNode;
  'extra-buttons'?: React.ReactNode;
}

export function SelectMenu({
  children,
  ...props
}: SelectMenuProps) {
  return (
    <div className="flex flex-col">
      <label htmlFor={props.id} className="pb-1 text-lum-text select-none">
        {children}
      </label>
      <SelectMenuRaw {...props}
        dropdown={(props.customDropdown || !props.values?.length)
          ? props.dropdown : undefined
        }
        extra-buttons={props['extra-buttons']}>
      </SelectMenuRaw>
    </div>
  );
}

export function SelectMenuRaw({
  values, className, panelClass = 'lum-bg-lum-input-bg', btnClass = 'lum-bg-transparent', noblur, nocloseonclick, customDropdown, hover, align,
  ...props
}: SelectMenuProps) {
  const [opened, setOpened] = useState(false);
  const [value, setValue] = useState(props.value?.toString() || (values && values[0]?.value.toString()) || '');
  const selectRef = useRef<HTMLSelectElement>(null);

  return (
    <div
      className={getClasses({
        'relative touch-manipulation': true,
        group: hover,
      })}
    >
      {values && (
        <select
          {...props}
          className="hidden"
          ref={selectRef}
        >
          {values.map((value, i) => {
            return (
              <option key={i} value={value.value}>{`${value.value}`}</option>
            );
          })}
        </select>
      )}
      <Dropdown
        opened={opened}
        className={getClasses({
          'w-full': true,
          [className ?? '']: !!className,
        })}
        onClick={(e) => {
          if (hover) return; // do not toggle on click if hover is enabled
          setOpened(!opened);
          if (nocloseonclick) return; // do not close on click if nocloseonclick is true
          const el = e.currentTarget;
          // close on click
          const listener = (e: MouseEvent) => {
            // check if the click is outside the button
            const path = e.composedPath();
            if (path.includes(el)) return;
            console.log('listener', e, el);

            // close the dropdown and remove the listener
            setOpened(false);
            document.removeEventListener('click', listener);
          };
          document.addEventListener('click', listener);
        }}
      >
        {customDropdown && props.dropdown}
        {!customDropdown && (
          <span>
            {values &&
              (values.find((v) => v.value.toString() === value)?.name
                ?? values[0].name)
            }
            {!values && props.dropdown}
          </span>
        )}
      </Dropdown>
      {hover && <div className="h-2 absolute w-full" />}
      <div className={getClasses({
        'absolute z-[1000] mt-2 transition-all ease-out': true,
        'backdrop-blur-lg': !noblur,
        'lum-scroll flex max-h-72 flex-col gap-1 overflow-auto rounded-lum border p-1 select-none motion-safe:transition-all': true,
        'left-0': align === 'left',
        'right-0': align === 'right',
        'left-1/2 -translate-x-1/2': align === 'center',
        'pointer-events-none scale-95 opacity-0': !opened,
        'duration-300 group-hover:pointer-events-auto group-hover:scale-100 group-hover:opacity-100 group-hover:duration-75': hover,
        'focus-within:pointer-events-auto focus-within:scale-100 focus-within:opacity-100 focus-within:duration-75': true,
        [panelClass]: true,
      })}
      >
        {values?.map(({ name, value }, i) => {
          return (
            <button type="button"
              className={getClasses({
                'lum-btn rounded-lum-1': true,
                [btnClass]: true,
              })}
              key={i}
              onClick={(e) => {
                // close the dropdown
                e.currentTarget.blur();
                setOpened(false);

                // set the value of the select element
                const select = selectRef.current;
                if (select) {
                  select.value = value.toString();
                  select.dispatchEvent(new Event('change', {
                    bubbles: true,
                    cancelable: true,
                  }));
                }
                setValue(value.toString());
              }}
            >
              {name}
            </button>
          );
        })}
        {props['extra-buttons']}
      </div>
    </div>
  );
}
